[package]
name = "playground"
version = "0.1.0"
authors = ["shantanu28sharma <shantanu28sharma@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
palette = "0.5"
raster = "0.2.0"

